name: Build

on:
  push:
    paths:
      - 'UI with Classes/**/*.4dm'
  pull_request:
    paths:
      - 'UI with Classes/**/*.4dm'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        uses: ./.github/actions/4d-build
        with:
          token: ${{ secrets.DLTK }}
